version: "3.8"

services:

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: finance

 api:

   build:
     context: .
     dockerfile: Dockerfile.api

   depends_on:
     - db

   command: >
     sh -c "
     python data/generate_data.py &&
     uvicorn api.main:app
     --host 0.0.0.0
     --port 8000
     "

   ports:
     - "8000:8000"
     
 dashboard:
   build:
     context: .
     dockerfile: Dockerfile.dashboard

   ports:
     - "8501:8501"

   depends_on:
     - api
